#!/bin/bash
# Script for submitting jobs

echo "Submitting Job to Largemem Queue..."
qsub 	-V \
	-q largemem \
	-l h_rt=24:00:00 \
	-pe 12way 24 \
	-N NBeanN$2k$3 \
	-M moorhsumsignup@gmail.com \
	-m beasn \
	-cwd \
	-o Rel_NBeanN$2k$3_output.txt \
	-e Rel_NBeanN$2k$3_error.txt \
	-b y \
	$*

